def generate_python_code(config, file_path="dataset.csv"):
    """
    Returns a string containing a complete Python script to reproduce the cleaning.
    """
    code = f"""
# Auto-generated by DataPrep Pro
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.utils import resample

# 1. Load Data
df = pd.read_csv('{file_path}')

# 2. Configured Pipeline
"""
    
    # Logic for Missing Values
    if config['missing_values']['enable']:
        strat = config['missing_values']['strategy']
        code += f"\n# Missing Values ({strat})\n"
        if strat == 'drop':
            code += "df.dropna(inplace=True)\n"
        else:
            code += f"num_cols = df.select_dtypes(include=np.number).columns\n"
            code += f"df[num_cols] = df[num_cols].fillna(df[num_cols].{strat}())\n"
            code += f"df.fillna(df.mode().iloc[0], inplace=True)\n"

    # Logic for Outliers
    if config['outliers']['enable']:
        code += f"\n# Outlier Treatment ({config['outliers']['method']})\n"
        code += "# (Simplified IQR logic for brevity)\n"
        code += "Q1 = df.quantile(0.25)\nQ3 = df.quantile(0.75)\nIQR = Q3 - Q1\n"
        code += "df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]\n"

    # Logic for Encoding
    if config['encoding']['enable']:
        method = config['encoding']['method']
        code += f"\n# Encoding ({method})\n"
        code += "cat_cols = df.select_dtypes(include=['object']).columns\n"
        if method == 'label':
            code += "for col in cat_cols:\n    df[col] = LabelEncoder().fit_transform(df[col])\n"
        else:
            code += "df = pd.get_dummies(df, columns=cat_cols, drop_first=True)\n"

    code += "\n# Save Result\ndf.to_csv('cleaned_data_reproduced.csv', index=False)\nprint('Done!')"
    
    return code